/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavLink: typeof import('./src/components/NavLink.vue')['default']
    NavTitle: typeof import('./src/components/NavTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperCard: typeof import('./src/components/SwiperCard.vue')['default']
    TripCard: typeof import('./src/components/TripCard.vue')['default']
  }
}
